#! /bin/sh

export XDG_CURRENT_DESKTOP=bspwm
export WAYLAND_DISPLAY=off

# xrandr --output eDP1 --off
sxhkd &
compton &

bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
xsetroot -cursor_name left_ptr

feh --bg-fill /home/ego/pics/wall/cityumbrella.jpg
polybar example

/usr/lib/kdeconnectd
sleep 2 && indicator-kdeconnect
