#! /bin/sh

export XDG_CURRENT_DESKTOP=xfce
export WAYLAND_DISPLAY=off

#xrandr --output eDP1 --off
sxhkd &
compton &

bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           12

bspc config bottom_padding         28
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a "Wrapper-2.0" state=floating
bspc rule -a "Thunar" state=floating
bspc rule -a "Zathura" state=tiled
bspc rule -a "libreoffice" state=tiled
bspc rule -a "libreoffice-calc" state=tiled
bspc rule -a "libreoffice-writer" state=tiled
bspc rule -a "libreoffice-impress" state=tiled
xsetroot -cursor_name left_ptr

/usr/lib/kdeconnectd
sleep 2 && indicator-kdeconnect
